# Generated by Django 3.1.5 on 2021-01-31 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=30)),
                ('status', models.IntegerField(choices=[(1, 'Shopping'), (2, 'Payment'), (3, 'Shipping'), (4, 'Recieved'), (5, 'Cancelled'), (6, 'Verification')], default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymongo_id', models.CharField(blank=True, max_length=50, null=True)),
                ('net', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('free_shipping', models.BooleanField(default=False)),
                ('payment_type', models.IntegerField(choices=[(1, 'Gcash'), (2, 'Cod')])),
                ('payment_status', models.IntegerField(choices=[(1, 'Paid'), (2, 'Inprogress'), (3, 'Expired'), (4, 'Cancelled')], default=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
