# Generated by Django 3.1.5 on 2021-02-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
